AllCops:
  TargetRubyVersion: 2.7.1
  Exclude:
    - "vendor/**/*"
    - "db/schema.rb"
    - "db/*"
    - "db/fixtures/**/*"
    - "tmp/**/*"
    - "bin/**/*"
    - "builds/**/*"
    - "Rakefile"
Style/Documentation:
  Enabled: false
Lint/AmbiguousBlockAssociation:
  Exclude:
    - "spec/**/*"

#### Turning these off for now.
#### These are useful but are hard to fix now
Metrics/AbcSize:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
  Max: 1000
Metrics/MethodLength:
  Enabled: false
  Max: 20
  Exclude:
    - "spec/**/*"
Metrics/ParameterLists:
  Enabled: false
Metrics/ModuleLength:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
  Exclude:
    - "spec/**/*"
###############################################

Layout/LineLength:
  Enabled: false

## Naming
Naming/AccessorMethodName:
  Enabled: false
Naming/PredicateName:
  Enabled: false
Naming/MethodName:
  Enabled: false

## Style
Style/RedundantSelf:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Style/FrozenStringLiteralComment:
  EnforcedStyle: never
Style/NumericPredicate:
  EnforcedStyle: comparison
Style/MultilineBlockChain:
  Enabled: false
Style/StringLiterals:
  EnforcedStyle: double_quotes
Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes
Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma
Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma
Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma
Style/CommentedKeyword:
  Enabled: false
# inline private for methods
Style/AccessModifierDeclarations:
  EnforcedStyle: inline
# this causes the 0 -> 0o issue when passing numbers prefixed
# with 0 into arguments (eg. chmod(0777) -> chmod(0o777))
Style/NumericLiteralPrefix:
  Enabled: false
# This below cop may have potential bug, bbatsov/rubocop#4118
Style/TernaryParentheses:
  Enabled: false
Style/GuardClause:
  Enabled: false
Style/Semicolon:
  Enabled: false
Style/Alias:
  Enabled: false
Style/HashEachMethods:
  Enabled: false
Style/HashTransformKeys:
  Enabled: false
Style/HashTransformValues:
  Enabled: false

## Layout
Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent
Layout/FirstArgumentIndentation:
  Enabled: true
Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent
Layout/MultilineArrayBraceLayout:
  EnforcedStyle: new_line
Layout/MultilineHashBraceLayout:
  EnforcedStyle: new_line
Layout/MultilineMethodCallBraceLayout:
  EnforcedStyle: symmetrical
Layout/MultilineMethodDefinitionBraceLayout:
  EnforcedStyle: new_line
Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation
Layout/ParameterAlignment:
  EnforcedStyle: with_fixed_indentation
Layout/MultilineOperationIndentation:
  EnforcedStyle: indented
Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented
Layout/FirstArrayElementLineBreak:
  Enabled: true
Layout/FirstHashElementLineBreak:
  Enabled: true
Layout/FirstMethodArgumentLineBreak:
  Enabled: true
Layout/FirstMethodParameterLineBreak:
  Enabled: true

Lint/RaiseException:
  Enabled: false
Lint/StructNewOverride:
  Enabled: false
